/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { MaterialXLoader } from "three/examples/jsm/loaders/MaterialXLoader.js";
import { DoubleSide } from "three";

export function JoltBolt(props) {
	const { nodes, materials } = useGLTF("/models/joltBolt.glb");

	// log out the maps
	return (
		<group {...props} dispose={null}>
			<mesh castShadow receiveShadow geometry={nodes.Cube002.geometry}>
				<meshPhysicalMaterial side={DoubleSide} color="gold" metalness={1} />
			</mesh>
		</group>
	);
}

useGLTF.preload("/models/joltBolt.glb");
